// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lnsitzfanpcfuibwxvsb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxuc2l0emZhbnBjZnVpYnd4dnNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1OTk4MDcsImV4cCI6MjA2MTE3NTgwN30.WEUlWJ8JU8POoHfsniyGSiSbdcpvOGaV-2cKYNyySEY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);